### ISSUE TITLE
When passing a state to the elevation prop on a Box, it throws an error but still works fine

### ISSUE THREAD

**Issue by jeffrey-carr** [mucyildiz/mafia#15]
Can be seen on LandingPage.js

**Comment by mucyildiz** [comment]
whats the error? cant get to my laptop rn

**Comment by jeffrey-carr** [comment]
"Invalid prop `elevation` supplied to `Box`." This error doesn't happen if you pass a value directly (e.g. elevation="small")

**Comment by mucyildiz** [comment]
ah yeah I think that's because el is an array and elevation prop is expecting a string, I'll fix that and push it to dev

**Comment by mucyildiz** [comment]
idiot @jcarr98
